/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\web\\a\\blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-1f962cbf",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f962cbf").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-21db2a0f",
    path: "/blogs/journey/2016/note01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21db2a0f").then(next)
    },
  },
  {
    name: "v-0daba14f",
    path: "/blogs/journey/2018/note01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0daba14f").then(next)
    },
  },
  {
    name: "v-0393dcef",
    path: "/blogs/journey/2019/note01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0393dcef").then(next)
    },
  },
  {
    name: "v-763939af",
    path: "/blogs/journey/2018/note02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-763939af").then(next)
    },
  },
  {
    name: "v-56a1e4a2",
    path: "/blogs/journey/2019/note03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56a1e4a2").then(next)
    },
  },
  {
    name: "v-3d3ca60f",
    path: "/blogs/journey/2019/note04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d3ca60f").then(next)
    },
  },
  {
    name: "v-b46b8322",
    path: "/blogs/journey/2019/note05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b46b8322").then(next)
    },
  },
  {
    name: "v-6c21754f",
    path: "/blogs/journey/2019/note02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c21754f").then(next)
    },
  },
  {
    name: "v-2588fcaf",
    path: "/blogs/journey/2020/note01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2588fcaf").then(next)
    },
  },
  {
    name: "v-0e57d6cf",
    path: "/blogs/journey/2019/note06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e57d6cf").then(next)
    },
  },
  {
    name: "v-26e72de2",
    path: "/blogs/journey/2021/note03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26e72de2").then(next)
    },
  },
  {
    name: "v-f503501a",
    path: "/blogs/journey/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f503501a").then(next)
    },
  },
  {
    path: "/blogs/journey/index.html",
    redirect: "/blogs/journey/"
  },
  {
    name: "v-f8025ea2",
    path: "/blogs/journey/2021/note02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f8025ea2").then(next)
    },
  },
  {
    name: "v-31867018",
    path: "/blogs/life/Pet.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31867018").then(next)
    },
  },
  {
    name: "v-48e51d88",
    path: "/blogs/life/Vlog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48e51d88").then(next)
    },
  },
  {
    name: "v-8a54937c",
    path: "/docs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8a54937c").then(next)
    },
  },
  {
    path: "/docs/index.html",
    redirect: "/docs/"
  },
  {
    name: "v-60483f9b",
    path: "/docs/notes/uniapp/Uniapp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60483f9b").then(next)
    },
  },
  {
    name: "v-0d5f5af5",
    path: "/docs/notes/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d5f5af5").then(next)
    },
  },
  {
    path: "/docs/notes/index.html",
    redirect: "/docs/notes/"
  },
  {
    name: "v-736bdc51",
    path: "/docs/notes/vue/VueCli4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-736bdc51").then(next)
    },
  },
  {
    name: "v-31afcc49",
    path: "/docs/notes/vuepress/FAQ.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-31afcc49").then(next)
    },
  },
  {
    name: "v-3163b919",
    path: "/docs/notes/vue/Axios.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3163b919").then(next)
    },
  },
  {
    name: "v-666eb00b",
    path: "/docs/notes/vue/Vue_V.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-666eb00b").then(next)
    },
  },
  {
    name: "v-1b71384f",
    path: "/blogs/journey/2021/note01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b71384f").then(next)
    },
  },
  {
    name: "v-62a2781b",
    path: "/docs/notes/vuepress/VuePress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62a2781b").then(next)
    },
  },
  {
    name: "v-8a07b27a",
    path: "/docs/notes/vue/Vuex_getters.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8a07b27a").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-15719b8e",
    path: "/tag/游记/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-15719b8e").then(next)
    },
    meta: {"pid":"tags","id":"游记"}
  },
  {
    path: "/tag/游记/index.html",
    redirect: "/tag/游记/"
  },
  {
    name: "v-46828558",
    path: "/tag/uniApp/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-46828558").then(next)
    },
    meta: {"pid":"tags","id":"uniApp"}
  },
  {
    path: "/tag/uniApp/index.html",
    redirect: "/tag/uniApp/"
  },
  {
    name: "v-322a45da",
    path: "/tag/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-322a45da").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tag/vue/index.html",
    redirect: "/tag/vue/"
  },
  {
    name: "v-5e08fc30",
    path: "/tag/VuePress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5e08fc30").then(next)
    },
    meta: {"pid":"tags","id":"VuePress"}
  },
  {
    path: "/tag/VuePress/index.html",
    redirect: "/tag/VuePress/"
  },
  {
    name: "v-4191ed9c",
    path: "/categories/旅程/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-4191ed9c").then(next)
    },
    meta: {"pid":"categories","id":"旅程"}
  },
  {
    path: "/categories/旅程/index.html",
    redirect: "/categories/旅程/"
  },
  {
    name: "v-14bbbf36",
    path: "/categories/前端/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-14bbbf36").then(next)
    },
    meta: {"pid":"categories","id":"前端"}
  },
  {
    path: "/categories/前端/index.html",
    redirect: "/categories/前端/"
  },
  {
    name: "v-6e4cbd38",
    path: "/tag/游记/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e4cbd38").then(next)
    },
    meta: {"pid":"tags","id":"游记"}
  },
  {
    path: "/tag/游记/page/2/index.html",
    redirect: "/tag/游记/page/2/"
  },
  {
    name: "v-c5aa3ebe",
    path: "/categories/旅程/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c5aa3ebe").then(next)
    },
    meta: {"pid":"categories","id":"旅程"}
  },
  {
    path: "/categories/旅程/page/2/index.html",
    redirect: "/categories/旅程/page/2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]