/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\web\\blog\\blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-065d8384",
    path: "/blogs/journey/2018/note01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-065d8384").then(next)
    },
  },
  {
    name: "v-1100c6fe",
    path: "/blogs/journey/2016/note01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1100c6fe").then(next)
    },
  },
  {
    name: "v-1a8d0c44",
    path: "/blogs/journey/2019/note01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a8d0c44").then(next)
    },
  },
  {
    name: "v-655ed69e",
    path: "/blogs/journey/2018/note02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-655ed69e").then(next)
    },
  },
  {
    name: "v-7856aac4",
    path: "/blogs/journey/2019/note03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7856aac4").then(next)
    },
  },
  {
    name: "v-5b47123e",
    path: "/blogs/journey/2019/note02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b47123e").then(next)
    },
  },
  {
    name: "v-d6204944",
    path: "/blogs/journey/2019/note05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d6204944").then(next)
    },
  },
  {
    name: "v-2c6242fe",
    path: "/blogs/journey/2019/note04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c6242fe").then(next)
    },
  },
  {
    name: "v-05051884",
    path: "/blogs/journey/2019/note06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05051884").then(next)
    },
  },
  {
    name: "v-14ae999e",
    path: "/blogs/journey/2020/note01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14ae999e").then(next)
    },
  },
  {
    name: "v-0a96d53e",
    path: "/blogs/journey/2021/note01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a96d53e").then(next)
    },
  },
  {
    name: "v-73246d9e",
    path: "/blogs/journey/2021/note02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73246d9e").then(next)
    },
  },
  {
    name: "v-489bf404",
    path: "/blogs/journey/2021/note03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-489bf404").then(next)
    },
  },
  {
    name: "v-0a9ba3a4",
    path: "/blogs/journey/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a9ba3a4").then(next)
    },
  },
  {
    path: "/blogs/journey/index.html",
    redirect: "/blogs/journey/"
  },
  {
    name: "v-0bccc8aa",
    path: "/blogs/life/Vlog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0bccc8aa").then(next)
    },
  },
  {
    name: "v-c577879a",
    path: "/docs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c577879a").then(next)
    },
  },
  {
    path: "/docs/index.html",
    redirect: "/docs/"
  },
  {
    name: "v-56877f66",
    path: "/docs/notes/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56877f66").then(next)
    },
  },
  {
    path: "/docs/notes/index.html",
    redirect: "/docs/notes/"
  },
  {
    name: "v-d683676c",
    path: "/docs/notes/uniapp/Uniapp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d683676c").then(next)
    },
  },
  {
    name: "v-b5263670",
    path: "/docs/notes/vue/Axios.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b5263670").then(next)
    },
  },
  {
    name: "v-22899880",
    path: "/docs/notes/vue/VueCli4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22899880").then(next)
    },
  },
  {
    name: "v-4b10488c",
    path: "/docs/notes/vue/Vue_V.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b10488c").then(next)
    },
  },
  {
    name: "v-331bb432",
    path: "/docs/notes/vue/Vuex_getters.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-331bb432").then(next)
    },
  },
  {
    name: "v-df618e90",
    path: "/docs/notes/vuepress/FAQ.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-df618e90").then(next)
    },
  },
  {
    name: "v-511465ca",
    path: "/docs/notes/vuepress/VuePress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-511465ca").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-15719b8e",
    path: "/tag/游记/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-15719b8e").then(next)
    },
    meta: {"pid":"tags","id":"游记"}
  },
  {
    path: "/tag/游记/index.html",
    redirect: "/tag/游记/"
  },
  {
    name: "v-46828558",
    path: "/tag/uniApp/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-46828558").then(next)
    },
    meta: {"pid":"tags","id":"uniApp"}
  },
  {
    path: "/tag/uniApp/index.html",
    redirect: "/tag/uniApp/"
  },
  {
    name: "v-322a45da",
    path: "/tag/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-322a45da").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tag/vue/index.html",
    redirect: "/tag/vue/"
  },
  {
    name: "v-5e08fc30",
    path: "/tag/VuePress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5e08fc30").then(next)
    },
    meta: {"pid":"tags","id":"VuePress"}
  },
  {
    path: "/tag/VuePress/index.html",
    redirect: "/tag/VuePress/"
  },
  {
    name: "v-4191ed9c",
    path: "/categories/旅程/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-4191ed9c").then(next)
    },
    meta: {"pid":"categories","id":"旅程"}
  },
  {
    path: "/categories/旅程/index.html",
    redirect: "/categories/旅程/"
  },
  {
    name: "v-14bbbf36",
    path: "/categories/前端/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-14bbbf36").then(next)
    },
    meta: {"pid":"categories","id":"前端"}
  },
  {
    path: "/categories/前端/index.html",
    redirect: "/categories/前端/"
  },
  {
    name: "v-6e4cbd38",
    path: "/tag/游记/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e4cbd38").then(next)
    },
    meta: {"pid":"tags","id":"游记"}
  },
  {
    path: "/tag/游记/page/2/index.html",
    redirect: "/tag/游记/page/2/"
  },
  {
    name: "v-c5aa3ebe",
    path: "/categories/旅程/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c5aa3ebe").then(next)
    },
    meta: {"pid":"categories","id":"旅程"}
  },
  {
    path: "/categories/旅程/page/2/index.html",
    redirect: "/categories/旅程/page/2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]