/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "游记": {
      "key": "游记",
      "scope": "tags",
      "path": "/tag/游记/",
      "pageKeys": [
        "v-21db2a0f",
        "v-0daba14f",
        "v-0393dcef",
        "v-763939af",
        "v-56a1e4a2",
        "v-3d3ca60f",
        "v-b46b8322",
        "v-6c21754f",
        "v-2588fcaf",
        "v-0e57d6cf",
        "v-26e72de2",
        "v-f8025ea2",
        "v-1b71384f"
      ]
    },
    "uniApp": {
      "key": "uniApp",
      "scope": "tags",
      "path": "/tag/uniApp/",
      "pageKeys": [
        "v-60483f9b"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-736bdc51",
        "v-3163b919",
        "v-666eb00b",
        "v-8a07b27a"
      ]
    },
    "VuePress": {
      "key": "VuePress",
      "scope": "tags",
      "path": "/tag/VuePress/",
      "pageKeys": [
        "v-62a2781b"
      ]
    }
  },
  "categories": {
    "旅程": {
      "key": "旅程",
      "scope": "categories",
      "path": "/categories/旅程/",
      "pageKeys": [
        "v-21db2a0f",
        "v-0daba14f",
        "v-0393dcef",
        "v-763939af",
        "v-56a1e4a2",
        "v-3d3ca60f",
        "v-b46b8322",
        "v-6c21754f",
        "v-2588fcaf",
        "v-0e57d6cf",
        "v-26e72de2",
        "v-f8025ea2",
        "v-1b71384f"
      ]
    },
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-60483f9b",
        "v-736bdc51",
        "v-3163b919",
        "v-666eb00b",
        "v-62a2781b",
        "v-8a07b27a"
      ]
    }
  },
  "timeline": {}
}