/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "游记": {
      "key": "游记",
      "scope": "tags",
      "path": "/tag/游记/",
      "pageKeys": [
        "v-065d8384",
        "v-1100c6fe",
        "v-1a8d0c44",
        "v-655ed69e",
        "v-7856aac4",
        "v-5b47123e",
        "v-d6204944",
        "v-2c6242fe",
        "v-05051884",
        "v-14ae999e",
        "v-0a96d53e",
        "v-73246d9e",
        "v-489bf404"
      ]
    },
    "uniApp": {
      "key": "uniApp",
      "scope": "tags",
      "path": "/tag/uniApp/",
      "pageKeys": [
        "v-d683676c"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-b5263670",
        "v-22899880",
        "v-4b10488c",
        "v-331bb432"
      ]
    },
    "VuePress": {
      "key": "VuePress",
      "scope": "tags",
      "path": "/tag/VuePress/",
      "pageKeys": [
        "v-511465ca"
      ]
    }
  },
  "categories": {
    "旅程": {
      "key": "旅程",
      "scope": "categories",
      "path": "/categories/旅程/",
      "pageKeys": [
        "v-065d8384",
        "v-1100c6fe",
        "v-1a8d0c44",
        "v-655ed69e",
        "v-7856aac4",
        "v-5b47123e",
        "v-d6204944",
        "v-2c6242fe",
        "v-05051884",
        "v-14ae999e",
        "v-0a96d53e",
        "v-73246d9e",
        "v-489bf404"
      ]
    },
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-d683676c",
        "v-b5263670",
        "v-22899880",
        "v-4b10488c",
        "v-331bb432",
        "v-511465ca"
      ]
    }
  },
  "timeline": {}
}