/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "游记",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/游记/","interval":[0,9]},{"path":"/tag/游记/page/2/","interval":[10,13]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "uniApp",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/uniApp/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "vue",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/vue/","interval":[0,4]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "VuePress",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/VuePress/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "旅程",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/旅程/","interval":[0,9]},{"path":"/categories/旅程/page/2/","interval":[10,13]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "前端",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/前端/","interval":[0,6]}],
  prevText: "Prev",
  nextText: "Next",
}]